name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

# Required permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Udhay-Adithya
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Generate Snake Animation" || exit 0
          git push origin main
