name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Udhay-Adithya
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - name: Push to GitHub
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/
          git commit -m "Generate Snake Animation"
          git push origin master
